language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wilham
  password:
    secure: glRa3ktsdf8I+NF8FWPYvccTmUPajRguXOXRckl8yAqpnKJAGKZH+sX0gfCbnlQ1xsMvcpw2BvAqgvEA6EO/EKuYVgxaUN0NQ6XoR9k8acXTJyfUQMDM9GVC+N9RKK6VVKJfUPrPZuExxBW7L6Fs0kTv5WwA5Tr3pRwvN9Lmca15K0AfHP595JcVXgg4xjV6EwHMdVZ+v2kVYJwzFfeGcnyMfiemGHN6SLs7b2MekiAkA53Yq0NqpChO6nI+BZhWWrg2TH7StobYuEISbgssTENk8f4OZCGEQY2qRyKufw6Gn82SKOHq1TzeP07q/lQb5PHvv7o4OqFeohfMPQW53Wo5jmHfzsrRwomveHZPE8SjOIOVBfPQ2YM/36Y1/iAEsqib0L9DDHyHAHmjgK0UZzNTOxosIYRxgF29uC64qaQpBema020QoHdbsdHUyMcpRrErdE6MIQxFdkwFrgmPwGw20RjNk0YByGHrzs6pyOFjuqF8WrbreekiEM518J1QA29S+6Lcz6++HNK5ayBmaUu7v+Hj6BARCMBOH7yswVPWriTgeHMnlxYhcEWUm5qKetccqFG05SMh3w29dkPcx1lQf25E3ljwgRDZveKk4Zto3a27WN8VFfb/9iy/A6ssLUh9AlJq2a98CH+pQJtraKpmE/qdTTOeRKn/vLu4FbE=
  on:
    tags: true
    repo: wilham-lynce/arkesel_py
    python: 3.8
